### ISSUE TITLE
Crash when 2 objects on screen.

### ISSUE THREAD

**Issue by jammy2232** [jammy2232/copious-couriers#19]
___________________________________________
############################################################################################
FATAL ERROR in
action number 1
of Draw Event
for object obj_farmer:

trying to index a variable which is not an array
 at gml_Object_obj_farmer_DrawEvent_1 (line 11) -         draw_text_transformed(button[1].x,button[1].y,ButtonOne,1,1,0);
############################################################################################

Error - Work around prevent 3 objects spawning

**Comment by Gabe-L** [comment]
Try starting game with two objects. If this crashes then implement further 'generated' checks in the draw and step events

**Comment by Gabe-L** [comment]
Two objects shouldn't be on screen at once now.
