### ISSUE TITLE
Wizard Event crashes the game

### ISSUE THREAD

**Issue by jammy2232** [jammy2232/copious-couriers#33]

**Comment by jammy2232** [comment]
___________________________________________
############################################################################################
FATAL ERROR in
action number 1
of  Step Event0
for object obj_wizard:

Push :: Execution Error - Variable Index [0,3] out of range [1,3] - -1.button(100066,3)
 at gml_Object_obj_wizard_StepNormalEvent_1 (line 16) -         if (button[i].pressed=1)
############################################################################################

**Comment by jammy2232** [comment]
Pretty sure it's not related to more than one object being generated at a time this one.

**Comment by jammy2232** [comment]
Doggo also crashes the game 


___________________________________________
############################################################################################
FATAL ERROR in
action number 1
of  Step Event0
for object obj_doggo:

Push :: Execution Error - Variable Index [0,3] out of range [1,3] - -1.button(100066,3)
 at gml_Object_obj_doggo_StepNormalEvent_1 (line 16) -         if (button[i].pressed=1)
############################################################################################

**Comment by Gabe-L** [comment]
Issue fixed: global.event_options was set in the step event when it should have been set in the collision event
